<?php
// $Id: vud.module,v 1.1.2.1 2009/05/26 11:36:55 lut4rp Exp $

/**
 * @file
 * Implements the core voting module.
 */

// Include the theme.inc file
module_load_include('inc', 'vud', 'vud.theme');

/**
 * Implementation of hook_help().
 */
function vud_help($path, $arg) {
  switch ($path) {
    case 'admin/help#vud':
      $output .= '<p>'. t('Provides a configurable up/down voting widget for other modules to use.') .'</p>';
      return $output;
  }
}

/**
 * Advanced menu settings callback.
 */
function vud_admin_advanced_settings() {
  $form['vote_widget_settings_advanced'] = array(
    '#type' => 'fieldset',
    '#title' => t('Advanced settings'),
  );
  $form['vote_widget_settings_advanced']['vud_reset_vote'] = array(
    '#type' => 'radios',
    '#title' => t('Allow users to reset their votes'),
    '#default_value' => variable_get('vud_reset_vote', 0),
    '#options' => array(0 => t('No'), 1 => t('Yes')),
    '#description' => t('If yes, a link will be displayed on nodes and comments that will allow users to reset their vote.'),
  );
  $form['vote_widget_settings_advanced']['vud_tag'] = array(
    '#type' => 'textfield',
    '#title' => t('Voting API tag'),
    '#default_value' => variable_get('vud_tag', 'vote'),
    '#description' => t('Since Vote Up/Down uses Voting API, all votes will be tagged with this term. (default: vote)<br />This tag is useful is you have deployed various modules that use Voting API. It should always be a unique value. Usually, there is NO need to change this.'),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_menu().
 */
function vud_menu() {
  $items = array();

  $items['admin/settings/voteupdown'] = array(
    'title' => 'Vote Up/Down',
    'description' => 'Control the functioning of Vote Up/Down.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vud_admin_advanced_settings'),
    'access arguments' => array('administer vote up/down'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/settings/voteupdown/advanced'] = array(
    'title' => 'Advanced',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['vud'] = array(
    'title' => 'Vote',
    'page callback' => 'vud_vote',
    'access arguments' => array('use vote up/down'),
    'type' => MENU_CALLBACK,
  );

  $items['node/%node/votes'] = array(
    'title' => 'Voting details',
    'page callback' => 'vud_tracker',
    'page arguments' => array(1),
    'access callback' => 'vud_node_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/%user/votes'] = array(
    'title' => 'Your votes',
    'page callback' => 'vud_user_votes',
    'page arguments' => array(1),
    'access arguments' => array('access vote up/down statistics'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implementation of hook_comment().
 */
function vud_comment(&$comment, $op) {
  switch ($op) {
    case 'view':
      if (variable_get('vud_widget_comment', 1)) {
        if (user_access('view up/down votes')) {
          $style = variable_get('vud_widget_style_comment', 0) == 1 ? '_alt' : '';
          $comment->comment = theme("vud_widget$style", $comment->cid, 'comment') . $comment->comment;
        }
      }
      break;
  }
}

/**
 * Comment template preprocess. Adding vud widget to variable list.
 */
function vud_preprocess_comment(&$variables) {
  if (user_access('view up/down votes')) {
    $comment = $variables['comment'];
    if ($comment->cid) {
      $style = variable_get('vud_widget_style_comment', 0) == 1 ? '_alt' : '';
      $variables['vud'] = theme("vud_widget$style", $comment->cid, 'comment');
    }
  }
}

/**
 * Implementation of hook_link().
 */
function vud_link($type, $object, $teaser = FALSE) {
  $links = array();
  switch ($type) {
    case 'node':
      $node = &$object;
      $node_type = in_array($node->type, variable_get('vud_node_types', array()), TRUE);
      $style = variable_get('vud_widget_style_node', 0) == 1 ? '_alt' : '';
      if ($node_type && user_access('view up/down votes')) {
        if (variable_get('vud_reset_vote', 0) && user_access('use vote up/down')) {
          $token = drupal_get_token("vud/$type/$node->nid/0");
          $links['vud_reset'] = array(
            'title' => t('Reset vote'),
            'href' => "vud/$type/$node->nid/0",
            'attributes' => array('title' => t('Reset your vote.')),
            'query' => drupal_get_destination() .'&token='. $token,
          );
        }
        if ($teaser && variable_get('vud_link_node', 0) && variable_get('vud_link_node', 0) != 2 && $style != "_alt") {
          $links['vud_points'] = array(
            'title' => theme('vud_points', $node->nid, $type),
            'html' => TRUE,
          );
        }
        else if (!$teaser && variable_get('vud_link_node', 0) > 1 && $style != "_alt") {
          $links['vud_points'] = array(
            'title' => theme('vud_points', $node->nid, $type),
            'html' => TRUE,
          );
        }
      }
      break;
    case 'comment':
      $comment = &$object;
      if (variable_get('vud_reset_vote', 0) && user_access('use vote up/down') && (variable_get('vud_widget_comment', 0) || variable_get('vud_link_comment', 0))) {
        $token = drupal_get_token("vud/$type/$comment->cid/0");
        $links['vud_reset_c'] = array(
          'title' => t('Reset vote'),
          'href' => "vud/$type/$comment->cid/0",
          'attributes' => array('title' => t('Reset your vote.')),
          'query' => drupal_get_destination() .'&token='. $token,
        );
      }
      if (variable_get('vud_link_comment', 0) && user_access('view up/down votes')) {
        $links['vud_points_c'] = array(
          'title' => theme('vud_points', $comment->cid, $type, NULL),
          'html' => TRUE,
        );
      }
      break;
  }

  return $links;
}

/**
 * Menu callback; display all votes for a user.
 */
function vud_user_votes() {
  if ($account = user_load(array('uid' => arg(1), 'status' => 1))) {
    if ($account->status || user_access('administer users')) {
      $header = array(
        array('data' => t('Node')),
        array('data' => t('Vote')),
        array('data' => t('Date'))
      );
      $sql = db_rewrite_sql("SELECT n.nid, n.title, v.value, v.timestamp FROM {node} n LEFT JOIN {votingapi_vote} v ON n.nid = v.content_id WHERE v.uid = %d AND v.tag = '%s' AND v.content_type = 'node' AND n.status = 1 ORDER BY v.timestamp DESC");
      $result = pager_query($sql, 25, 0, NULL, $account->uid, variable_get('vud_tag', 'vote'));
      while ($node = db_fetch_object($result)) {
        $rows[] = array(
          l($node->title, 'node/'. $node->nid),
          $node->value,
          t('!time ago', array('!time' => format_interval(time() - $node->timestamp)))
        );
      }
      drupal_set_title(check_plain($account->name));
      $output = theme('table', $header, $rows);
      $output .= theme('pager', NULL, 25);

      return $output;
    }
    else {
      drupal_access_denied();
    }
  }
  else {
    drupal_not_found();
  }
}

/**
 * Function for the main voting handler with Ajax support.
 */
function vud_vote($type, $cid, $value, $tag = NULL, $ajax = FALSE, $alt = FALSE) {
  if (is_numeric($cid) && is_numeric($value) && isset($_REQUEST['token']) && drupal_valid_token($_REQUEST['token'], "vud/$type/$cid/$value")) {
    $vote = array();
    // Sanity-check the incoming values.
    if ($value > 0) {
      $vote['value'] = 1;
    }
    else if ($value < 0) {
      $vote['value'] = -1;
    }
    else {
      $vote['value'] = 0;
    }

    $vote['value_type'] = 'points';

    $tag = $tag ? $tag : variable_get('vud_tag', 'vote');
    $vote['tag'] = $tag;

    // Do the voting via Voting API.
    if ($uid = _vud_get_uid()) {
      if ($vote['value'] == 0) {
        $criteria = array('content_type' => $type, 'content_id' => $cid, 'uid' => $uid, 'tag' => $tag);
        votingapi_delete_votes(votingapi_select_votes($criteria));
        votingapi_recalculate_results($type, $cid);
      }
      else {
        $vote['content_id'] = $cid;
        $vote['content_type'] = $type;
        $vote['uid'] = $uid;
        $votes = array(0 => $vote);
        votingapi_set_votes($votes);
      }
    }

    if ($ajax) {
      $style = ($alt == TRUE ? 'alt' : '');
      print theme('vud_points', $cid, $type, NULL, $style);
      exit();
    }
    else {
      drupal_goto(drupal_get_destination());
    }
  }
}

/**
 * Themeing functions for widget and points display.
 * Each of the functions below has a separate description of its own.
 */

/**
 * Preprocessing function for the widget in the alternate +1 style.
 */
function template_preprocess_vud_widget_alt(&$variables) {
  global $user;
  $cid = $variables['cid'];
  $type = $variables['type'];
  $tag = isset($variables['tag']) ? $variables['tag'] : variable_get('vud_tag', 'vote');

  drupal_add_css(drupal_get_path('module', 'vud') .'/vud.css');
  drupal_add_js(drupal_get_path('module', 'vud') .'/ajax_vud.js');

  $variables['points'] = theme('vud_points', $cid, $type, $tag, 'alt');
  if (user_access('use vote up/down') && ($user->uid)) {
    $criteria = array(
      'content_type' => $type,
      'content_id' => $cid,
      'uid' => _vud_get_uid(),
      'tag' => $tag,
    );
    $user_vote = votingapi_select_single_vote_value($criteria);

    if ($user_vote > 0) {
      $variables['class'] = 'vote-up-act';
    }
    else {
      $variables['class'] = 'vote-up-inact';
    }

    $token = drupal_get_token("vud/$type/$cid/1");
    $variables['title'] = url("vud/$type/$cid/1/$tag/1", array('query' => 'token='. $token));
    $variables['link'] = l('', "vud/$type/$cid/1/$tag", array(
                                               'attributes' => array(
                                                 'class' => $variables['class'],
                                                 'title' => t('Vote up')
                                               ),
                                               'query' => drupal_get_destination() .'&token='. $token,
                                              )
                                            );
  }
  else {
    $variables['class'] = 'up-inact';
    $variables['title'] = t('You must login to vote!');
  }
}

/**
 * Preprocess function for the points in the normal display style.
 */
function template_preprocess_vud_points(&$variables) {
  $tag = isset($variables['tag']) ? $variables['tag'] : variable_get('vud_tag', 'vote');

  $criteria = array(
    'content_type' => $variables['type'],
    'content_id' => $variables['cid'],
    'value_type' => 'points',
    'tag' => $tag,
    'function' => 'sum'
  );
  $vote_result = (int)votingapi_select_single_result_value($criteria);
  if ($vote_result > 0) {
    $variables['class'] = 'positive';
    $variables['points'] = '+'. $vote_result;
  }
  else {
    $variables['points'] = $vote_result;
    if ($vote_result < 0) {
      $variables['class'] = 'negative';
    }
    else {
      $variables['class'] = 'neutral';
    }
  }
  $variables['label'] = format_plural($vote_result, 'point', 'points');
  $variables['points_labelled'] = format_plural($vote_result, '1 point', '@count points');
  if (isset($variables['style'])) {
    $variables['template_files'][] = 'vud_points_'. $variables['style'];
  }
}

/**
 * Get a user ID for voting.
 */
function _vud_get_uid() {
  global $user;
  if ($user->uid) {
    $uid = $user->uid;
  }
  else {
    $uid = NULL;
  }
  return $uid;
}

/**
 * Check whether the current user has access to the given permission for the
 * given node. This requires both that they have access the required permission,
 * and that the node type is enabled for vote up/down.
 * @param $node
 *   A node object
 * @param $perm
 *   (Optional) the name of a permission to pass to user_access()
 * @return boolean TRUE if the user has access to the node vote up/down statistics.
 */
function vud_node_access($node, $perm = 'access vote up/down statistics') {
  if (user_access($perm)) {
    return in_array($node->type, variable_get('vud_node_types', array()), TRUE);
  }
  return FALSE;
}
